// these are actions
export const cartTypes = {
  ADD_TO_CART: "cart/ADD_TO_CART",
  REMOVE_CART: "cart/REMOVE_CART",
  INCREASE_QUANTITY: "cart/INCREASE_QUANTITY",
  CLEAR_CART: "cart/CLEAR_CART",
  HANDLE_PRODUCT_ID: "cart/HANDLE_PRODUCT_ID",
};
export const adminCart = {
  HANDLE_LOGIN: "HANDLE_LOGIN",
  HANDLE_LOGOUT: "HANDLE_LOGOUT",
  LOGIN_DATA: "LOGIN_DATA",
  LOADING: "LOADING",
};
